Markdown
Caribbean-Online-Judge/Web-Frontend pull request #17
Opened 2021-12-14 23:44 UTC by Kosmo00

close #16

2021-12-27 00:52 UTC, cl8dep requested changes
We need seriously thinking in a solution to do business logic in another way for example via Redux or Context but the UI components should be independent of its business logic.

2021-12-27 00:52 UTC, cl8dep commented on src/pages/_app.page.tsx
> -               {router.pathname.startsWith("/account") ? (
Please move this logic to an independent function to get more clear render function

2021-12-27 00:52 UTC, cl8dep commented on src/pages/admin/problems/add.page.tsx
> +   const mdKaTeX = `This is to display the
Remove this variable

2021-12-27 00:52 UTC, cl8dep commented on src/pages/admin/problems/add.page.tsx
> +      Object.entries(problemData).forEach((entie) => {
Entie? It's should be entry

2021-12-27 00:52 UTC, cl8dep commented on src/pages/admin/problems/add.page.tsx
> +   const disableButton =
The forma should be validate using some solution to do that. For example formstate

2021-12-28 23:48 UTC, cl8dep requested changes

2021-12-28 23:48 UTC, cl8dep commented on package.json
> +    "remark-gfm": "^3.0.1"
What the hell is this?

2021-12-28 23:48 UTC, cl8dep commented on src/pages/admin/problems/add.page.tsx
> +         <Controller
This logic can be implemented using a self created component to avoid repeat code

2021-12-29 00:05 UTC, jesusr00 commented on package.json
> +    "remark-gfm": "^3.0.1"
remark-gfm? 
Not idea, I'll remove it

2022-01-09 02:38 UTC, merged